language: python
cache: pip
python:
  - "3.6"

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - ./manage.py migrate
install:
  - pip install -r requirements.txt
  - pip install flake8 pylint pylint_django
script:
  - flake8 .
  - pylint --load-plugins pylint_django BuyBitcoin
  - pytest
